name: Synchronize Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: lainbo/cpu-mark
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: pnpm install

    - name: Run pnpm fetch
      run: pnpm run fetch

    - name: Check for changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --staged --quiet; then
          echo "文件相同，不需要提交，任务结束。"
        else
          echo "检测到文件变化，正在创建提交..."
          git commit -m "Automatic data update"
          git push
          echo "提交完成，任务结束。"
